### ISSUE TITLE
costcla.model is not working with latest version of sklearn 

### ISSUE THREAD

**Issue by arjunpuri7** [albahnsen/CostSensitiveClassification#15]

**Comment by arjunpuri7** [comment]
sir, 
      I want to use costcla library on my datasets as I am importing  from costcla import models I am facing error that no module of sklearn.cross_validation. As it present in sklearn.model_selection. please help me to uses this package on my datasets

**Comment by anilkumarpanda** [comment]
The code repository has been updated to work with sklearn.model_selection but it has not been pushed to pypi . To use the code :
1) Clone the repository to your local environment .
2) cd CostSensitiveClassification
3) pip install .

You should be able to use the latest version of the code . A few minor changes may be required to make to tutorial notebook work .

**Comment by hnslyh** [comment]
You need to change the sentense in Anaconda3\Lib\site-packages\costcla-0.5-py3.7.egg\costcla\models, open cost_ensemble.py. Then change [from sklearn.cross_validation import train_test_split] to [sklearn.model_selection import train_test_split]

**Comment by albahnsen** [comment]
Done. Sorry for the delay
