### ISSUE TITLE
Shape of the cost matrix

### ISSUE THREAD

**Issue by dhruvghulati-zz** [albahnsen/CostSensitiveClassification#3]
Is it necessary to create a 4 column cost matrix for each training and test set per `cost_mat[C_FP,C_FN,C_TP,C_TN]`? I only have one cost for each training instance. 

What do you recommend in this? Can my cost just be the cost of classifying the instance as positive `(C_FP)`, and then would you advise to leave the rest at 0?

Also, does the value of the cost matter? Or is it more the distribution of the cost vector across `C_FP, C_FN` etc?

**Comment by albahnsen** [comment]
@dhruvghulati The issue with assigning cost to 0 in all cases except the `C_FP` is that the algorithms will predict everything as negative. Then, it really depends on how your costs means. I will suggest trying to explain the `C_FP` in relation to `C_FN`

Indeed, what matters the most is the distribution.

**Comment by dhruvghulati-zz** [comment]
OK understood, so one thing I was contemplating is just calling the `C_FP` the same as `C_FN`, and then giving 0 to everything else? Thanks @albahnsen !

**Comment by albahnsen** [comment]
Not really, in that case the effects will cancel each other and it would be
the same as running a cost-insensitive classifier.
