### ISSUE TITLE
Support for Pandas DataFrame 

### ISSUE THREAD

**Issue by GoingMyWay** [albahnsen/CostSensitiveClassification#8]
I guess currently this library doesn't support taking Pandas DataFrame as input data because the following error will be raised

```
KeyError: '[58976 73597   747 ..., 32194 57641 57730] not in index'
```

so to use this library, one must call DataFrame's  `.as_matrix()` to transfer DataFrame into numpy ndarray.

**Comment by albahnsen** [comment]
Indeed when those functions were developed most work was done in numpy. It should be an easy fix.

**Comment by GoingMyWay** [comment]
@albahnsen Since it is not a bug, and I just wanna report this situation. I'll close this issue. Thank you!
